version: '3.8'

services:
  app:
    container_name: ${PROJECT_NAME}_app
    image: node:17-alpine
    restart: unless-stopped
    command: npm install && npm start
    ports:
      - ${APP_PORT}:${APP_DOCKER_PORT}
    working_dir: /app
    volumes:
      - ./app/:/app
    environment:
      APP_DOCKER_PORT: ${APP_DOCKER_PORT}
    depends_on:
      - mysql
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 1

  # api:
  #   container_name: ${PROJECT_NAME}_api
  #   image: node:17-alpine
  #   restart: unless-stopped
  #   command: sh -c "npm install && npm run start"
  #   ports:
  #     - ${API_PORT}:${API_DOCKER_PORT}
  #   working_dir: /api
  #   volumes:
  #     - ./api/:/api
  #   environment:
  #     API_DOCKER_PORT: ${API_DOCKER_PORT}
  #   depends_on:
  #     - mysql
  #   mem_limit: 512m
  #   mem_reservation: 128M
  #   cpus: 1

  mysql:
    image: mysql:5.7
    container_name: ${PROJECT_NAME}_mysql
    restart: unless-stopped
    volumes: 
        - ./mysql/conf.d:/etc/mysql/conf.d
        - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 2

volumes:
  mysql: