version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:stable
    depends_on:
      - api
      - app
      - mysql
    networks:
      - internal
    volumes:
      - ./nginx/image-files/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  app:
    container_name: ${PROJECT_NAME}_app
    image: ${APP_NODE_IMAGE}
    restart: unless-stopped
    command: sh -c "npm install && npm start"
    ports:
      - ${APP_PORT}:${APP_DOCKER_PORT}
    working_dir: /app
    volumes:
      - ./app/:/app
      - ./api/prisma/:/app/prisma
    environment:
      PORT: ${APP_DOCKER_PORT}
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${PROJECT_NAME}_mysql:${MYSQL_PORT}/${MYSQL_DATABASE}
      ACCESS_JWT_SECRET: ${ACCESS_JWT_SECRET}
      REFRESH_JWT_SECRET: ${REFRESH_JWT_SECRET}
    depends_on:
      - mysql
    mem_limit: 1024m
    mem_reservation: 128M
    cpus: ${APP_CPUS}
    networks:
      - internal

  vue:
    container_name: ${PROJECT_NAME}_vue
    image: ${VUE_NODE_IMAGE}
    restart: unless-stopped
    command: sh -c "npm install && npx vite --host"
    ports:
      - ${VUE_PORT}:${VUE_DOCKER_PORT}
    working_dir: /vue
    volumes:
      - ./vue/:/vue
    environment:
      PORT: ${VUE_DOCKER_PORT}
    depends_on:
      - mysql
    mem_limit: 1024m
    mem_reservation: 128M
    cpus: ${VUE_CPUS}
    networks:
      - internal

  api:
    container_name: ${PROJECT_NAME}_api
    image: ${API_NODE_IMAGE}
    restart: unless-stopped
    command: sh -c "npm install && npm run start"
    ports:
      - ${API_PORT}:${API_DOCKER_PORT}
    working_dir: /api
    volumes:
      - ./api/:/api
    environment:
      PORT: ${API_DOCKER_PORT}
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${PROJECT_NAME}_mysql:${MYSQL_PORT}/${MYSQL_DATABASE}
      CORE_COUNT: ${API_CPUS}
      ACCESS_JWT_SECRET: ${ACCESS_JWT_SECRET}
      REFRESH_JWT_SECRET: ${REFRESH_JWT_SECRET}
    depends_on:
      - mysql
    mem_limit: 2048m
    mem_reservation: 256M
    cpus: ${API_CPUS}
    networks:
      - internal

  mysql:
    image: mariadb:${MARIADB_VERSION:-latest}
    container_name: ${PROJECT_NAME}_mysql
    restart: unless-stopped
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    mem_limit: 1024m
    mem_reservation: 256M
    cpus: ${MYSQL_CPUS}
    ports:
      - 8000:${MYSQL_PORT}
    networks:
      - internal

  v2:
    container_name: ${PROJECT_NAME}_app_v2
    image: node:17-alpine
    restart: unless-stopped
    command: sh -c "npm install && npm run dev"
    ports:
      - ${V2_PORT}:${V2_DOCKER_PORT}
    working_dir: /v.2
    volumes:
      - ./v.2/:/v.2
    environment:
      PORT: ${V2_DOCKER_PORT}
      CORE_COUNT: ${V2_CPUS}
    depends_on:
      - mysql
    mem_limit: 4096m
    mem_reservation: 512M
    cpus: ${V2_CPUS}

  # Old School Admin.
  phpmyadmin:
    container_name: ${PROJECT_NAME}_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - mysql
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: ${PROJECT_NAME}_mysql
      PMA_PORT: ${MYSQL_PORT}
      PMA_ARBITRARY: 1
    links:
      - mysql

networks:
  internal:
    driver: bridge

volumes:
  mysql:
