module.exports = async (username, email, password) => {
    return {
        username: username,
        email: email,
        password: await v_to_sha256(password),
        created_at: new Date(),
        updated_at: new Date(),
        role: 'user',
        status: 'active',
        verified: false,
        firstName: null,
        lastName: null,
        phone: null,
        address: null,
        city: null,
        state: null,
        zip: null,
        country: null,
        avatar: null,
        cover: null,
        about: null,
        website: null,
        facebook: null,
        twitter: null,
        google: null,
        linkedin: null,
        youtube: null,
        github: null,
        instagram: null,
        language: null,
        ip: null,
        last_login: null,
        last_ip: null,
        timezone: null,
        stripe: null,
        card: null,
        card_brand: null,
        card_exp_month: null,
        card_exp_year: null,
        card_last: null,
        card_country: null,
        device: null,
        device_id: null,
        device_uuid: null,
        device_version: null,
        device_model: null,
        device_brand: null,
        device_manufacturer: null,
        device_platform: null,
        device_time: null,
        device_locale: null,
        login_blocked: null,
        login_blocked_time: null,
        login_blocked_expire: null,
        login_blocked_reason: null,
    };
};
